paths:
  spotify:
    raw_play_history:
      local: "./data/testing/raw/spotify_play_history"
      prod: ""
  location:
    bronze:
      local: "./data/testing/bronze/location"
      prod: "s3://me-dashboard-doug/bronze/location"
  health:
    bronze:
      local: "./data/testing/bronze/health"
      prod: "s3://me-dashboard-doug/bronze/health"
  workout:
    bronze:
      local: "./data/testing/bronze/workout"
      prod: "s3://me-dashboard-doug/bronze/workout"
  screen_time:
    iphone_bronze:
      local: "./data/testing/bronze/screen-time/iphone"
      prod: "s3://me-dashboard-doug/bronze/screen-time/iphone"
    mac_bronze:
      local: "./data/testing/bronze/screen-time/mac"
      prod: "s3://me-dashboard-doug/bronze/screen-time/mac"